name: GreatLifeSteal
version: "${version}"
main: io.github.zrdzn.minecraft.greatlifesteal.GreatLifeStealPlugin
api-version: 1.13
authors:
  - zrdzn
  - some0ne3
description: A recently popular Minecraft plugin for life stealing system in SMP servers.
softdepend:
  - PlaceholderAPI
permissions:
  greatlifesteal.command.hearts.set:
    default: op
  greatlifesteal.command.hearts.add:
    default: op
  greatlifesteal.command.hearts.remove:
    default: op
  greatlifesteal.command.lives:
    default: op
    children:
      greatlifesteal.command.lives.self:
        default: true
  greatlifesteal.command.withdraw:
    default: op
    children:
      greatlifesteal.command.withdraw.self:
        default: true
  greatlifesteal.command.reload:
    default: op
  greatlifesteal.command.eliminate:
    default: op
  greatlifesteal.command.revive:
    default: op
  greatlifesteal.notify.update:
    default: op
commands:
  lifesteal:
    aliases:
      - gls
  eliminate: {}
  revive: {}

